apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-hubii
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-hubii
  template:
    metadata:
      labels:
        app: devops-hubii
    spec:
      containers:
      - name: devops-hubii
        image: devops-hubii:1.0
        ports:
        - containerPort: 8080
        env:
        - name: APP_ENV
          value: "dev"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15