name: DevOps Hubii CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Validate Python syntax
        run: python -m py_compile app/main.py

      - name: Build Docker image
        run: docker build -f docker/Dockerfile -t devops-hubii:1.0 .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: devops-hubii:1.0
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1